### ISSUE TITLE
shadow-bleeding Chapter 4.2 - toon shader with levels

### ISSUE THREAD

**Issue by PaezRice** [PacktPublishing/Unity-2018-Shaders-and-Effects-Cookbook-Third-Edition#1]
The example in Chapter 4.2 where celshading gets implemented - by using levels to snap instead of a toon ramp map - causes shadow-bleeding.

Unity3D version:       2018.2.12f1
OS:                            Windows 10 (build: 17134)
GPU:                          Nvidia GTX 970
GPU-driver:               416.34 (proprietary)

I managed to fix it by adding:
`if(NdotL <= 0.0) NdotL = 0.0;`
to the surface shader right after the initialization of `NdotL`

**Comment by PaezRice** [comment]
otherwise you could just calculate NdotL like so:
`float NdotL = max(0, dot(s.Normal, lightDir));`
which is the way it's also done in later chapters

**Comment by jodoran** [comment]
Thanks for writing in, I've adjusted the code and made the fix.
