### ISSUE TITLE
Question : max value of shrunken cel value is slightly over 1.0.

### ISSUE THREAD

**Issue by IJEMIN** [PacktPublishing/Unity-2018-Shaders-and-Effects-Cookbook-Third-Edition#2]
The codes on page 286, I understand we have to divide multiplied value with  _CelShadingLevels for shrinking value range to 0-1.

`half cel = floor(NdotL * _CelShadingLevels) / (_CelShadingLevels - 0.5);`

But I can't understand why divide value with (_CelShadingLevels - 0.5), not _CelShadingLevels, that will make value range slightly bigger than 0-1, like 0-1.2, making slightly brighter.

Is there a reason for this? or It just matters of style?

**Comment by jodoran** [comment]
More style-based. Note that the floor function will remove any decimal value.
